import { Metadata } from "next";
import React from "react";
import { getAllUsers } from "@/lib/usersApi";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

export default async function UsersPage() {
  const usersData: Promise<User[]> = getAllUsers();

  const users = await usersData;

  const renderUsers = users.map((user) => (
    <>
      <p key={user.id}>
        <Link href={`/users/${user.id}`}>{user.name}</Link>
      </p>
    </>
  ));

  return (
    <section>
      <h2>
        <Link href="/Home"></Link>
        <br />
        {renderUsers}
      </h2>
    </section>
  );
}
