// applies to all subpages
import React from "react";
import styles from "./styles.module.css";

export const metadata = {
  title: "About page",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>About Navbar</nav>
      <main className={styles.main}>{children}</main>
    </>
  );
}
